import os

## SINGLY INFO, NEEDS TO BE UNIQUE PER APP
SINGLY_CLIENT_ID = 
SINGLY_CLIENT_SECRET = 
# lvh.me is just a domain name for localhost
SINGLY_REDIRECT_URI = 

## PLAID INFO
PLAID_CLIENT_ID = 
PLAID_CLIENT_SECRET =
PLAID_REDIRECT_URI = 

# Make this unique, and don't share it with anybody.
SECRET_KEY = 

## DROPBOX INFO
DROPBOX_APP_KEY = 
DROPBOX_APP_SECRET = 
# ACCESS_TYPE should be 'dropbox' or 'app_folder' as configured for your app
DROPBOX_ACCESS_TYPE = 
#DROPBOX_REDIRECT_URI = 
DROPBOX_REDIRECT_URI = 

## TWITTER INFO
TWITTER_CONSUMER_KEY = 
TWITTER_CONSUMER_SECRET = 
TWITTER_REDIRECT_URI = 

## LINKEDIN INFO
LINKEDIN_API_KEY = 
LINKEDIN_API_SECRET = 
LINKEDIN_REDIRECT_URI = 

## FOURSQUARE INFO
FOURSQUARE_CLIENT_ID = 
FOURSQUARE_CLIENT_SECRET = 
FOURSQUARE_REDIRECT_URI = 

## FACEBOOK INFO
FACEBOOK_CLIENT_ID = 
FACEBOOK_CLIENT_SECRET = 
FACEBOOK_REDIRECT_URI = 

## GOOGLE INFO
GOOGLE_CLIENT_ID = 
GOOGLE_CLIENT_SECRET = 
GOOGLE_EMAIL_ADDRESS = 
GOOGLE_REDIRECT_URI = 

## MINT INFO
MINT_EMAIL = 
MINT_PASSWORD = 



